### ISSUE TITLE
JavaScript Capstone Project

### ISSUE THREAD

**Issue by egichuhis** [egichuhis/tv-shows-capstone#33]
This project was done by @egichuhis  and @lucy-sees .

Please review the project.

Changes made:

- **List structure layout**
- **Fetch TV Shows from API**
- **Display the fetched TV Shows**
- **Like a TV Show(s)**
- **Increment like counter and update view**
- **Popup window to show more TV Show mdetails**
- **Post comments to Involvement API**
- **Fetch comments from API and display**

**Comment by AmaduKamara** [comment]
# Status: Invalid Submission ❌

Hi Team,, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not have a Pull Request. You submitted an Issue Link but you're required to submit a Pull Request, not an issue. 👍🏽

- [ ] Kindly merge all your feature branches from all team members and then create the PR to be reviewed from the dev/development branch. The PR structure should look like this `main from `development` 👍🏽

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._
```
